<template>
    <div>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><u><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>CONDITIONS D&rsquo;UTILISATION DE L&rsquo;APPLICATION AMELEMIASSI</span></u></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Les pr&eacute;sentes conditions g&eacute;n&eacute;rales d&rsquo;utilisation (ci-apr&egrave;s d&eacute;nomm&eacute;es &laquo; CGU &raquo;) ont pour objet l&rsquo;encadrement juridique des modalit&eacute;s d&rsquo;utilisation de l&rsquo;application &laquo; Am&eacute;l&eacute;miassi &raquo; (ci-apr&egrave;s d&eacute;nomm&eacute;e l&rsquo;&laquo; Application &raquo;) &eacute;dit&eacute;e par la soci&eacute;t&eacute; <strong>&laquo;&nbsp;MIAFI SARL&nbsp;&raquo;</strong></span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>En installant l&rsquo;Application sur votre terminal et/ou en acc&eacute;dant &agrave; l&rsquo;Application, en tant que visiteur et/ou utilisateur, vous acceptez sans condition ni r&eacute;serve l&rsquo;int&eacute;gralit&eacute; des CGU d&eacute;finies ci-apr&egrave;s. Si vous ne souhaitez pas accepter les pr&eacute;sentes CGU, nous vous demandons de ne pas acc&eacute;der &agrave; l&rsquo;Application. Toute visite et/ou utilisation de l&rsquo;Application doit se faire dans le respect des pr&eacute;sentes CGU.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>MENTIONS LEGALES&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;&eacute;dition est assur&eacute;e par La soci&eacute;t&eacute; &laquo;&nbsp;MIAFI&nbsp;&raquo;, Soci&eacute;t&eacute; &agrave; Responsabilit&eacute; Limit&eacute; (SARL) immatricul&eacute;e au registre du commerce et du cr&eacute;dit mobilier (RCCM) sous le num&eacute;ro ______________ ayant son si&egrave;ge &agrave; Adidogom&eacute;, BP : _____ Lom&eacute; Togo, T&eacute;l: ________.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 1. DEFINITIONS&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Les termes d&eacute;butant par une majuscule au sein des pr&eacute;sentes CGU, qu&rsquo;ils soient utilis&eacute;s indiff&eacute;remment au singulier ou au pluriel, auront, la signification qui leur est donn&eacute;e ci-apr&egrave;s:&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; <strong>Application&nbsp;</strong>&raquo; d&eacute;signe l&rsquo;application logicielle &laquo; Am&eacute;l&eacute;miassi &raquo; &eacute;dit&eacute;e et fournie par &laquo; MIAFI &raquo; , donnant acc&egrave;s aux Services, qui est disponible gratuitement dans le &laquo; Google Play Store &raquo; de Google pour &ecirc;tre t&eacute;l&eacute;charg&eacute;e par l&rsquo;Utilisateur sur son terminal Android. L&rsquo;Application comprend &eacute;galement les Contenus, les logiciels, les programmes, les outils (de programmation, de navigation, &hellip;), les bases de donn&eacute;es, les syst&egrave;mes d&rsquo;exploitation, la documentation et tous autres &eacute;l&eacute;ments et services qui la compose, les mises &agrave; jour et les nouvelles versions qui peuvent &ecirc;tre apport&eacute;es &agrave; l&rsquo;Application par &laquo; Am&eacute;l&eacute;miassi &raquo;.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; <strong>Contenu&nbsp;</strong>&raquo; d&eacute;signe sans que cette liste soit limitative, la structure de l&rsquo;Application, le contenu &eacute;ditorial, les dessins, les illustrations, les images, les photographies, les chartes graphiques, les marques, les logos, les sigles, les d&eacute;nominations sociales, les oeuvres audiovisuelles, les oeuvres multim&eacute;dias, les contenus visuels, les contenus audio et sonores, ainsi que tout autre contenu pr&eacute;sent au sein de l&rsquo;Application et/ou tout autre &eacute;l&eacute;ment composant l&rsquo;Application.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; <strong>Services&nbsp;</strong>&raquo; d&eacute;signent les diff&eacute;rentes fonctionnalit&eacute;s et services propos&eacute;es par l&rsquo;Application.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; <strong>Site&nbsp;</strong>&raquo; d&eacute;signe le site web officiel de &laquo; MIAFI &raquo; dont l&rsquo;adresse est la suivante : www.togocom.tg&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; <strong>Utilisateur&nbsp;</strong>&raquo; ou &laquo; <strong>Vous&nbsp;</strong>&raquo; d&eacute;signe une personne physique majeure ou mineure ayant pr&eacute;alablement obtenu l&rsquo;autorisation de ses parents ou de la personne investie de l&rsquo;autorit&eacute; parentale, et ayant t&eacute;l&eacute;charg&eacute; l&rsquo;Application pour ses besoins propres, dans le cadre d&rsquo;un usage strictement personnel et non commercial, sans but lucratif direct ou indirect.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 2. OBJET DE L&rsquo;APPLICATION&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;application &laquo; Am&eacute;l&eacute;miassi permet &agrave; l&rsquo;utilisateur d&rsquo;acc&eacute;der &agrave; diff&eacute;rents services, notamment :&nbsp;</span></p>
<ul style="list-style-type: undefined;margin-left:29px;">
    <li><span style='font-family:"Arial",sans-serif;'>Transfert d&rsquo;argent&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>Retrait d&rsquo;argent</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>Historique des transactions</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Cette liste est non exhaustive et peut &ecirc;tre modifi&eacute;e &agrave; tout moment sans que la responsabilit&eacute; de &laquo; MIAFI &raquo; ne puisse &ecirc;tre engag&eacute;e &agrave; ce titre par qui que ce soit.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 3. ACCES A L&rsquo;APPLICATION&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Pour acc&eacute;der et utiliser l&rsquo;Application, l&rsquo;Utilisateur doit disposer d&rsquo;un t&eacute;l&eacute;phone/terminal compatible et d&rsquo;un acc&egrave;s au r&eacute;seau Internet.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;Application est t&eacute;l&eacute;chargeable gratuitement depuis la plateforme &laquo; Google Play Store &raquo;.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 4. APPLICATION DES CGU&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Les CGU sont applicables &agrave; tout Utilisateur de l&rsquo;Application et des Services. L&rsquo;Utilisateur est invit&eacute; &agrave; lire attentivement les CGU qui sont accessibles :&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;margin-bottom:.9pt;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;color:#C00000;'>-&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Sur la page de t&eacute;l&eacute;chargement Play store&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;margin-bottom:.9pt;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;color:#C00000;'>-&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Sur le Site web de &laquo; MIAFI &raquo;&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;color:#C00000;'>-&nbsp;</span><span style='font-family:"Arial",sans-serif;'>Dans le menu d&eacute;roulant de l&rsquo;application&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;Application devra faire l&rsquo;objet d&rsquo;une mise &agrave; jour r&eacute;guli&egrave;re. A cet &eacute;gard, toute Application t&eacute;l&eacute;charg&eacute;e par un Utilisateur a une validit&eacute; limit&eacute;e dans le temps, compte tenu de ses mises &agrave; jour &agrave; t&eacute;l&eacute;charger imp&eacute;rativement et des &eacute;ventuelles &eacute;volutions techniques, l&eacute;gislatives ou r&eacute;glementaires, dont l&rsquo;&eacute;diteur n&rsquo;a pas le contr&ocirc;le.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Les CGU sont susceptibles d&rsquo;&ecirc;tre modifi&eacute;es &agrave; tout moment et sans pr&eacute;avis par l&rsquo;&eacute;diteur&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 5. PROPRIETE INTELLECTUELLE DE L&rsquo;APPLICATION&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; MIAFI &raquo; est propri&eacute;taire exclusif de tous les droits de propri&eacute;t&eacute; intellectuelle aff&eacute;rents &agrave; l&rsquo;Application et son Contenu. Ainsi, les marques, logos et signes ainsi que tous les contenus de l&rsquo;application sont prot&eacute;g&eacute;s par le droit d&rsquo;auteur. L&rsquo;utilisateur s&rsquo;engage &agrave; une utilisation de l&rsquo;application dans un cadre strictement priv&eacute;. Toute autre utilisation n&eacute;cessite une autorisation expresse de l&rsquo;&eacute;diteur.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Sans pr&eacute;judice des dispositions de la pr&eacute;sente disposition, aucune des dispositions des CGU ne peut &ecirc;tre interpr&eacute;t&eacute;e comme une cession, un transfert, une vente, une concession, une licence, un pr&ecirc;t, une location, une autorisation d&rsquo;exploitation consentie directement ou indirectement &laquo; MIAFI &raquo; au profit de l&rsquo;Utilisateur sur l&rsquo;Application son Contenu et/ou les Services.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 6. LICENCE D&rsquo;UTILISATION&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; MIAFI &raquo; conc&egrave;de &agrave; l&rsquo;Utilisateur un droit personnel d&rsquo;utilisation de l&rsquo;Application, du Contenu et des Services, non exclusif, r&eacute;vocable, non cessible, non transf&eacute;rable, mondial et gratuit uniquement pour ses besoins propres dans le cadre de l&rsquo;utilisation de l&rsquo;Application et des Services, &agrave; l&rsquo;exclusion de toute autre finalit&eacute;. Il est strictement interdit &agrave; l&rsquo;Utilisateur d&rsquo;acc&eacute;der et /ou d&rsquo;utiliser les codes source de l&rsquo;Application et /ou des composants logiciels de l&rsquo;Application. L&rsquo;Utilisateur n&rsquo;acquiert aucun droit de propri&eacute;t&eacute; intellectuelle sur l&rsquo;Application, le Contenu et /ou les Services ni aucun autre droit que ceux conf&eacute;r&eacute;s par les pr&eacute;sentes. La pr&eacute;sente licence ne conf&egrave;re aucun droit d&rsquo;utilisation &agrave; l&rsquo;Utilisateur sur le Contenu. L&rsquo;Utilisateur s&rsquo;interdit donc de reproduire, repr&eacute;senter, adapter et/ou exploiter l&rsquo;un et l&rsquo;autre Contenu. L&rsquo;Utilisateur s&rsquo;engage express&eacute;ment &agrave; ce que l&rsquo;utilisation de l&rsquo;Application ne porte en aucun cas atteinte aux droits de &laquo; MIAFI &raquo; et notamment &agrave; ce que cette utilisation ne constitue pas un acte de contrefa&ccedil;on, de concurrence d&eacute;loyale ou parasitaire du Contenu.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 7. OBLIGATIONS DE L&rsquo;UTILISATEUR&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;Utilisateur s&rsquo;engage express&eacute;ment :&nbsp;</span></p>
<ul style="list-style-type: undefined;margin-left:26px;">
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; t&eacute;l&eacute;charger l&rsquo;Application sur son &eacute;quipement exclusivement pour un usage personnel et non marchand;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; ne pas reproduire de fa&ccedil;on permanente ou provisoire l&rsquo;Application, en tout ou partie, par tout moyen et sous toute forme ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&nbsp;&agrave; ne pas utiliser de logiciels ou de proc&eacute;d&eacute;s destin&eacute;s &agrave; copier le Contenu sans l&rsquo;autorisation pr&eacute;alable &eacute;crite de &laquo; MIAFI &raquo;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; ne pas proc&eacute;der &agrave; toute adaptation, modification, traduction, transcription, arrangement, compilation, d&eacute;compilation, assemblage, d&eacute;sassemblage, transcodage, ni appliquer la r&eacute;tro-ing&eacute;nierie (ou &laquo; Reverse Engineering &raquo;) de tout ou partie de l&rsquo;Application, des Services et/ou du Contenu ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; ne pas exporter l&rsquo;Application, de fusionner tout ou partie de l&rsquo;Application avec d&rsquo;autres programmes informatiques ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; ne proc&eacute;der &agrave; des courtes citations, analyses et reproductions destin&eacute;es &agrave; des revues de presse ainsi qu&rsquo;aux autres utilisations express&eacute;ment autoris&eacute;es par la loi dans les limites et conditions fix&eacute;es par cette derni&egrave;re et sous r&eacute;serve notamment de citer le nom des auteurs et la source &eacute;ditoriale&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; renoncer express&eacute;ment &agrave; utiliser des logiciels ou dispositifs susceptibles de perturber le bon fonctionnement de l&rsquo;Application, ni &agrave; engager d&rsquo;action de nature &agrave; imposer une charge disproportionn&eacute;e pour les infrastructures de &laquo; MIAFI &raquo;;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; ne pas extraire ou r&eacute;utiliser, y compris &agrave; des fins priv&eacute;es, sans autorisation pr&eacute;alable &eacute;crite de &laquo; MIAFI &raquo;, une partie substantielle ou non du contenu des bases de donn&eacute;es et archives constitu&eacute;es par l&rsquo;Application ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; ne pas mettre en place des syst&egrave;mes susceptibles de pirater l&rsquo;Application et/ou le Contenu en tout ou partie, ou de nature &agrave; violer les pr&eacute;sentes CGU ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; informer &laquo; MIAFI &raquo; &nbsp;d&egrave;s la connaissance d&rsquo;un acte de piratage et en particulier de toute utilisation illicite ou non contractuelle de l&rsquo;Application et/ou du Contenu quel que soit le mode de diffusion ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&agrave; ne pas vendre, louer, sous-licencier ou distribuer de quelque fa&ccedil;on que ce soit l&rsquo;Application et/ou le Contenu &agrave; des tiers.&nbsp;</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 8. PROTECTION DES DONNEES PERSONNELLES&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;application assure une collecte d&rsquo;informations personnalis&eacute;es de l&rsquo;utilisateur dans le respect des dispositions de la Loi N&deg; 2019-014 du 29 octobre 2019 relative &agrave; la protection des donn&eacute;es &agrave; caract&egrave;re personnel. Ces informations collect&eacute;es ont pour finalit&eacute; exclusive de permettre/faciliter l&rsquo;utilisation de l&rsquo;application.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 9. DISPONIBILITE DE L&rsquo;APPLICATION&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; MIAFI &raquo; s&rsquo;engage &agrave; faire ses meilleurs efforts pour s&eacute;curiser l&rsquo;acc&egrave;s, la consultation et l&rsquo;utilisation des Services de l&rsquo;Application. L&rsquo;Application est accessible 24 heures sur 24, 7 jours sur 7 sauf en cas de force majeure ou de survenance d&rsquo;un &eacute;v&egrave;nement hors du contr&ocirc;le de &laquo; MIAFI &raquo; et sous r&eacute;serve des &eacute;ventuelles pannes et interventions de maintenance n&eacute;cessaires au bon fonctionnement de l&rsquo;Application. Les interventions de maintenance pourront &ecirc;tre effectu&eacute;es sans que les Utilisateurs aient &eacute;t&eacute; pr&eacute;alablement avertis.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 10. LIENS HYPERTEXTE - COOKIES&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Des liens hypertextes peuvent &ecirc;tre pr&eacute;sents sur une page de l&rsquo;application. L&rsquo;utilisateur est inform&eacute; qu&rsquo;en cliquant sur ces liens, il est possible qu&rsquo;il soit dirig&eacute; vers d&rsquo;autres contenus sur lesquels l&rsquo;&eacute;diteur n&rsquo;a pas de contr&ocirc;le et ne saurait en aucun cas &ecirc;tre responsable en ce qui les concerne.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;utilisateur est &eacute;galement inform&eacute; que lors de ses acc&egrave;s &agrave; l&rsquo;application, un cookie peut s&rsquo;installer automatiquement sur son terminal. Les cookies sont de petits fichiers stock&eacute;s temporairement sur le disque dur du terminal de l&rsquo;Utilisateur et qui sont n&eacute;cessaires &agrave; l&rsquo;acc&egrave;s &agrave; l&rsquo;application. Ils sont utilis&eacute;s pour am&eacute;liorer la qualit&eacute; des services de l&rsquo;application. En acc&eacute;dant &agrave; l&rsquo;application, l&rsquo;utilisateur les accepte.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 11. LIMITATION DE RESPONSABILITE&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;acc&egrave;s et l&rsquo;utilisation de l&rsquo;Application se font aux risques et p&eacute;rils de l&rsquo;Utilisateur. L&rsquo;Application et le logiciel sont fournis &laquo; tel quel &raquo; et &laquo; comme disponible &raquo; sans garantie quelle qu&rsquo;elle soit. Il appartient &agrave; tout Utilisateur de prendre toutes les mesures appropri&eacute;es de fa&ccedil;on &agrave; prot&eacute;ger ses propres donn&eacute;es et/ ou logiciels stock&eacute;s sur ses &eacute;quipements informatique et t&eacute;l&eacute;phonique contre toute atteinte. L&rsquo;Utilisateur d&eacute;clare conna&icirc;tre et accepter les caract&eacute;ristiques et les limites du r&eacute;seau Internet et, notamment les caract&eacute;ristiques fonctionnelles et des performances techniques de ce r&eacute;seau, les probl&egrave;mes li&eacute;s &agrave; la connexion et/ou &agrave; l&rsquo;acc&egrave;s au r&eacute;seau Internet et/ou aux sites web, les probl&egrave;mes li&eacute;s &agrave; la disponibilit&eacute; et &agrave; l&rsquo;encombrement des r&eacute;seaux, les probl&egrave;mes li&eacute;s &agrave; la d&eacute;faillance ou &agrave; la saturation des r&eacute;seaux, les probl&egrave;mes li&eacute;s au temps de transit, &agrave; l&rsquo;acc&egrave;s aux informations mises en ligne, aux temps de r&eacute;ponse pour afficher, consulter, interroger ou autrement transf&eacute;rer des donn&eacute;es, les risques d&rsquo;interruption, l&rsquo;absence de protection de certaines donn&eacute;es contre des d&eacute;tournements &eacute;ventuels ou piratage, les risques de contamination par d&rsquo;&eacute;ventuels virus circulant sur les dits r&eacute;seaux, etc&hellip; pour lesquelles la responsabilit&eacute; de Togocom ne saurait &ecirc;tre engag&eacute;e.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&laquo; MIAFI &raquo; ne peut &ecirc;tre tenue pour responsable :&nbsp;</span></p>
<ul style="list-style-type: undefined;margin-left:26px;">
    <li><span style='font-family:"Arial",sans-serif;'>&nbsp;en cas de d&eacute;faut, de perte, de retard ou d&rsquo;erreur de transmission de donn&eacute;es qui sont ind&eacute;pendants de sa volont&eacute;;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>de l&rsquo;envoi de messages et /ou de donn&eacute;es et &agrave; une adresse fausse, erron&eacute;e ou incompl&egrave;te ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>&nbsp;si des donn&eacute;es ne lui parvenaient pas, pour quelque raison que ce soit, ou si les donn&eacute;es qu&rsquo;elle re&ccedil;oit &eacute;taient illisibles ou impossibles &agrave; traiter ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>au cas o&ugrave; l&rsquo;Utilisateur ne parvenait &agrave; acc&eacute;der ou &agrave; utiliser le Site de t&eacute;l&eacute;chargement de l&rsquo;application, l&rsquo;Application et/ou les Services pour quelque raison que ce soit ;&nbsp;</span></li>
    <li><span style='font-family:"Arial",sans-serif;'>si, pour quelque raison que ce soit, la connexion devait &ecirc;tre interrompue.&nbsp;</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Par ailleurs, &laquo; MIAFI &raquo; d&eacute;cline toute responsabilit&eacute; en cas de mauvaise utilisation du terminal et/ou d&rsquo;incident li&eacute; &agrave; l&rsquo;utilisation du terminal lors de l&rsquo;utilisation de l&rsquo;Application. &laquo; MIAFI &raquo; ne saurait en aucun cas &ecirc;tre tenue responsable de tout dommage, de quelque nature que ce soit, caus&eacute; aux Utilisateurs, &agrave; leurs terminaux, &agrave; leurs &eacute;quipements informatiques et t&eacute;l&eacute;phoniques et aux donn&eacute;es qui y sont stock&eacute;es ni des cons&eacute;quences pouvant en d&eacute;couler sur leur activit&eacute; personnelle, professionnelle ou commerciale.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 12. EVOLUTION DES CONDITIONS GENERALES D&rsquo;UTILISATION</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Les CGU applicables sont celles en vigueur &agrave; la date de la connexion et de l&rsquo;utilisation de l&rsquo;Application par l&rsquo;Utilisateur. &laquo; MIAFI &raquo; &nbsp;se r&eacute;serve le droit de modifier, &agrave; tout moment, tout ou partie, des dispositions des CGU sans pr&eacute;avis ni information pr&eacute;alable des Utilisateurs afin de les adapter aux &eacute;volutions des Services, aux &eacute;volutions techniques, l&eacute;gales ou jurisprudentielles ou lors de la mise en place de nouvelles prestations. Les modifications &eacute;ventuellement apport&eacute;es par &laquo; MIAFI &raquo; aux CGU seront port&eacute;es &agrave; la connaissance des Utilisateurs par leur simple mise en ligne. Elles sont r&eacute;put&eacute;es accept&eacute;es sans r&eacute;serve par tout Utilisateur qui acc&egrave;de &agrave; l&rsquo;Application post&eacute;rieurement &agrave; ladite mise en ligne. &laquo; MIAFI &raquo; invite donc tout Utilisateur &agrave; consulter r&eacute;guli&egrave;rement les CGU. Tout nouveau Service int&eacute;grant de nouvelles techniques ou nouvelles caract&eacute;ristiques am&eacute;liorant la qualit&eacute; des Services existants seront aussi soumis aux pr&eacute;sentes CGU, sauf disposition expresse contraire.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 13. RESILIATION&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>L&rsquo;Utilisateur peut d&eacute;sinstaller l&rsquo;application de son terminal &agrave; tout moment, ce qui mettra fin &agrave; son adh&eacute;sion aux pr&eacute;sentes CGU. &laquo; MIAFI &raquo; est libre de suspendre, arr&ecirc;ter l&rsquo;application &agrave; tout moment. Dans ce cas, &laquo; MIAFI &raquo; pr&eacute;viendra dans les meilleurs d&eacute;lais l&rsquo;Utilisateur avant qu&rsquo;il ne soit mis fin au Service.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>Article 14. CONTACT&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Toute question relative &agrave; l&rsquo;Application et/ou aux Services et aux pr&eacute;sentes CGU sera adress&eacute;e au service client &laquo; MIAFI &raquo; accessible via le ________.&nbsp;</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>ARTICLE 15. LOI APPLICABLE &ndash;REGLEMENT DE DIFFERENT&nbsp;</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Les pr&eacute;sentes CGU sont r&eacute;gies au droit togolais. En cas d&rsquo;absence de r&eacute;solution &agrave; l&rsquo;amiable d&rsquo;un litige n&eacute; entre les parties li&eacute;es &agrave; l&rsquo;utilisation de l&rsquo;application, les tribunaux togolais sont comp&eacute;tents pour en conna&icirc;tre.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><u><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'><span style="text-decoration:none;">&nbsp;</span></span></u></strong></p>
    </div>
</template>