<template>
    <div>
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;'><strong><u><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>POLITIQUE DE CONFIDENTIALITE</span></u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Veuillez prendre le temps de lire avec attention les informations suivantes, de mani&egrave;re &agrave; bien comprendre notre position et nos pratiques concernant vos informations personnelles et la mani&egrave;re dont nous les utiliserons. Si vous ne souscrivez pas aux dispositions de la pr&eacute;sente politique, nous vous prions de ne pas acc&eacute;der &agrave; nos services et de ne pas les utiliser.&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>En utilisant notre, notre application mobile (&laquo; notre <strong>App&nbsp;</strong>&raquo;) ou tout autre produit et service (appel&eacute;s collectivement &laquo; nos <strong>Services&nbsp;</strong>&raquo;), vous acceptez les pratiques d&eacute;crites dans la pr&eacute;sente Politique de confidentialit&eacute; (&laquo; cette <strong>Politique&nbsp;</strong>&raquo;).</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Cette politique s&rsquo;applique &eacute;galement lorsque vous participez &agrave; nos projets de recherche. Outre la pr&eacute;sente Politique, nous pouvons adopter d&rsquo;autres politiques de protection de la vie priv&eacute;e en certaines occasions sp&eacute;cifiques, lorsque nous collectons ou traitons des informations personnelles vous concernant (par exemple, lorsque vous nous expliquez pourquoi vous envoyez de l&rsquo;argent &agrave; vos proches), afin que vous soyez pleinement inform&eacute;s de la mani&egrave;re dont nous utilisons vos donn&eacute;es et des motifs de cette utilisation. La pr&eacute;sente Politique compl&egrave;te ces autres Politiques de confidentialit&eacute; et ne saurait en aucun cas les remplacer.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>1. &Agrave; PROPOS DE CETTE POLITIQUE</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>La pr&eacute;sente Politique, s&rsquo;applique &agrave; votre utilisation de nos services, lorsque ces services sont mis &agrave; disposition ou accessibles via notre Site ou notre Application, et apr&egrave;s que vous ayez t&eacute;l&eacute;charg&eacute; ou visionn&eacute; une copie de notre Application sur votre appareil mobile ou portable (votre <strong>Appareil</strong>).</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Cette Politique a &eacute;t&eacute; mise &agrave; jour pour la derni&egrave;re fois le 06 juillet 2022. Elle s&rsquo;applique aux utilisateurs de nos services r&eacute;sidant au Togo et &agrave; l&rsquo;&eacute;tranger.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Lorsque nous utilisons d&rsquo;autres termes et expressions en majuscules dans la pr&eacute;sente</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Politique (tels que Contrat, Profil et Transaction), ceux-ci ont la m&ecirc;me signification&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>2. QUI SOMMES-NOUS ?</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><span style='font-family:"Arial",sans-serif;'>Toute information personnelle fournie ou collect&eacute;e par nos Services est contr&ocirc;l&eacute;e par la soci&eacute;t&eacute; &laquo;&nbsp;MIAFI&nbsp;&raquo; propri&eacute;taire de l&rsquo;application des transactions financi&egrave;res &laquo;&nbsp;Am&eacute;l&eacute;miassi&nbsp;&raquo;, Soci&eacute;t&eacute; &agrave; Responsabilit&eacute; Limit&eacute; (SARL) immatricul&eacute;e au registre du commerce et du cr&eacute;dit mobilier (RCCM) sous le num&eacute;ro ______________ ayant son si&egrave;ge &agrave; Adidogom&eacute;, BP : _____ Lom&eacute; Togo, T&eacute;l: ________.</span></p>
<p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:justify;line-height:150%;'><strong><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Times New Roman",serif;'>3. QUI EST NOTRE RESPONSABLE DE LA PROTECTION DES DONN&Eacute;ES ?</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous avons nomm&eacute; un <strong>Responsable &agrave; la protection des donn&eacute;es&nbsp;</strong>que vous pouvez contacter si vous avez des questions concernant cette Politique ou si vous pensez que nous avons enfreint la loi sur la protection sur la Protection des donn&eacute;es et/ou le R&egrave;glement G&eacute;n&eacute;ral sur la Protection des Donn&eacute;es (RGPD). Veuillez joindre la soci&eacute;t&eacute; et la personne indiqu&eacute;e par mail :&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:21px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>4</span></strong><strong><span style='font-size:21px;line-height:150%;font-family:"Arial",sans-serif;'>.&nbsp;</span></strong><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>LES MODIFICATIONS APPORT&Eacute;ES &Agrave; CETTE POLITIQUE</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous sommes susceptibles de modifier &agrave; tout moment cette Politique, et chaque fois que nous le ferons, nous vous en informerons en publiant une version r&eacute;vis&eacute;e sur notre site et notre application. Veuillez consulter cette Politique &agrave; chaque fois que vous r&eacute;alisez une transaction (en effet, elle peut avoir &eacute;t&eacute; mise &agrave; jour depuis votre enregistrement initial &agrave; nos Services ou depuis votre derni&egrave;re transaction).</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>5. VISITEURS DE NOTRE SITE (&Agrave; L&rsquo;EXCLUSION DES ABONN&Eacute;S &Agrave; NOS SERVICES)</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Informations personnelles collect&eacute;es :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous recueillons des cookies et des</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Informations associ&eacute;es.&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Partage de vos informations personnelles :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous partagerons ces informations avec les personnes suivantes :</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ul style="margin-bottom:0cm;list-style-type: undefined;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><strong><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>&nbsp;</span></strong><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>Notre personnel (mais leur utilisation devra &ecirc;tre limit&eacute;e &agrave; l&rsquo;exercice de leurs</span></li>
    </ul>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Fonctions et se conformer au motif du traitement, et notamment pour apporter une aide &agrave; la client&egrave;le et &agrave; des fins de d&eacute;pannage, d&rsquo;analyse des donn&eacute;es, de tests, de recherche de statistiques et d&rsquo;enqu&ecirc;te) ;&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Conservation de vos informations personnelles :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Ces informations sont conserv&eacute;es pendant les dur&eacute;es indiqu&eacute;es dans la Politique en mati&egrave;re de cookies, puis seront supprim&eacute;es automatiquement. Toutefois :</span></p>
<ul style="list-style-type: undefined;">
    <li><strong><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>&nbsp;</span></strong><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>si nous devons, pour des raisons l&eacute;gales, conserver ces informations plus longtemps, nous les conserverons pendant toute la p&eacute;riode requise ; et/ou</span></li>
    <li><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>Lorsque ces informations sont utilis&eacute;es dans le cadre d&rsquo;une proc&eacute;dure judiciaire (m&ecirc;me potentielle), elles seront conserv&eacute;es pendant toute la dur&eacute;e de cette proc&eacute;dure (et de toute mesure d&rsquo;ex&eacute;cution).</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>6. S&rsquo;ABONNER &Agrave; NOS SERVICES</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Informations personnelles collect&eacute;es :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Lorsque vous vous abonnez &agrave; nos services :<strong>- &nbsp; &nbsp; Cr&eacute;ation d&rsquo;un profil&nbsp;</strong>- vous devrez indiquer votre adresse &eacute;lectronique et un mot de passe (nous n&rsquo;aurons pas acc&egrave;s &agrave; votre mot de passe et ne le divulguerons donc pas). Veuillez noter que vous devrez cr&eacute;er un profil pour pouvoir effectuer des transactions ;</span></p>
<ul style="list-style-type: undefined;">
    <li><strong><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>Effectuer des transactions&nbsp;</span></strong><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>- vous devrez fournir les informations personnelles suppl&eacute;mentaires suivantes :</span></li>
    <li><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>vos nom, adresse, date de naissance, num&eacute;ro de t&eacute;l&eacute;phone, informations sur vos moyens de paiement (carte de d&eacute;bit/cr&eacute;dit ou compte bancaire) ; et</span></li>
    <li><span style='line-height:150%;font-family:"Arial",sans-serif;font-size:16px;'>sur notre demande, certains documents d&rsquo;identification d&eacute;livr&eacute;s par le gouvernement, notamment votre passeport, votre permis de conduire et/ou vos cartes d&rsquo;identit&eacute; d (ainsi qu&rsquo;une photo de vous avec vos documents d&rsquo;identification), des documents prouvant votre adresse, et</span></li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>certaines informations concernant la personne &agrave; qui vous envoyez de l&rsquo;argent (le <strong>destinataire</strong>), afin que nous puissions faciliter les transferts de fonds, y compris de la part du destinataire : le nom et le pr&eacute;nom, l&rsquo;adresse, le num&eacute;ro de t&eacute;l&eacute;phone (facultatif) et les coordonn&eacute;es de l&rsquo;&eacute;tablissement financier du b&eacute;n&eacute;ficiaire lui permettant d&rsquo;encaisser le transfert de fonds (il peut s&rsquo;agir des coordonn&eacute;es du compte bancaire du b&eacute;n&eacute;ficiaire, si ce dernier doit recevoir les fonds directement sur son compte bancaire, ou encore des coordonn&eacute;es d&rsquo;un &eacute;tablissement financier, si une option d&rsquo;encaissement est disponible) ; employeur et la preuve du mode de financement de votre transaction (relev&eacute; bancaire ou fiche de paie, par exemple).</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull; Importation de contacts&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>: nous pouvons vous donner la possibilit&eacute; d&rsquo;importer des contacts* depuis votre Gmail, Yahoo Mail ou d&rsquo;autres fournisseurs de messagerie, et vous permettre de les saisir manuellement pour les inviter &agrave; devenir membres de nos Services (nous ne collectons pas le nom d&rsquo;utilisateur et le mot de passe du compte de messagerie depuis lequel vous souhaitez importer vos contacts, car vous les indiquez directement &agrave; ce fournisseur de messagerie et, apr&egrave;s votre approbation, ceux-ci nous</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Envoient vos contacts &eacute;lectroniques).</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull; Si vous utilisez notre service de recommandation par e-mail&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>pour informer un ami* de nos Services, vous devrez fournir le nom et l&rsquo;adresse e-mail de votre ami.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Avant de nous donner acc&egrave;s aux coordonn&eacute;es d&rsquo;une autre personne, vous devez au pr&eacute;alable obtenir son consentement pour la transmission de ses informations personnelles, et nous lui ferons savoir que vous nous avez fourni ses coordonn&eacute;es.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Si vous avez :</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>import&eacute; vos contacts, nous enverrons sur vos instructions un e-mail d&rsquo;invitation et au maximum un courriel de rappel les invitant &agrave; visiter notre Site. Nous conservons ces informations dans le seul but d&rsquo;envoyer cet e-mail ; et/ou</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>recommand&eacute; un ami, nous enverrons automatiquement &agrave; votre ami un e-mail et au maximum un e-mail de rappel l&rsquo;invitant &agrave; visiter notre Site. Nous conservons ces informations dans le seul but d&rsquo;envoyer cet e-mail et d&rsquo;effectuer le suivi du succ&egrave;s de votre recommandation.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>En outre, nous collectons les informations suivantes :</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>journaux de transactions qui contiennent des informations sur votre transaction (ces informations sont &eacute;galement fournies sous la forme d&rsquo;un re&ccedil;u envoy&eacute; par courrier &eacute;lectronique que vous recevrez lorsque vous effectuerez une transaction), contenant un num&eacute;ro de r&eacute;f&eacute;rence unique de transaction associ&eacute; &agrave; chaque transaction ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>informations que vous nous transmettez lorsque vous contactez le service client&egrave;le (nous g&eacute;n&eacute;rons &eacute;galement automatiquement un num&eacute;ro de client pour vous lorsque vous vous inscrivez &agrave; nos Services, pour pouvoir vous identifier au sein de notre</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Syst&egrave;me CRM) ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>informations que nous recevons (l&eacute;galement) de sources tierces (telles que les services de v&eacute;rification d&rsquo;identit&eacute;, les services de bases de donn&eacute;es &eacute;lectroniques, les agences de notation de cr&eacute;dit, les partenaires commerciaux, les sous-traitants de services techniques, de paiement et de livraison, les r&eacute;seaux publicitaires et les prestataires de services d&rsquo;&eacute;tudes de march&eacute;) ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>les informations techniques suivantes seront automatiquement collect&eacute;es lorsque vous utiliserez notre Application :</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>le mat&eacute;riel et les logiciels que vous utilisez lorsque vous acc&eacute;dez &agrave; nos Services (ce qui peut inclure le type d&rsquo;appareil que vous utilisez), un identifiant unique d&rsquo;appareil (par exemple, le num&eacute;ro IMEI de votre appareil, ou le num&eacute;ro de mobile utilis&eacute; par ce dernier), votre adresse IP, les informations du r&eacute;seau mobile, votre syst&egrave;me d&rsquo;exploitation mobile, le type de navigateur mobile que vous utilisez, les pages auxquelles vous acc&eacute;dez sur notre Site, et les autres sites Web que vous visitez avant d&rsquo;acc&eacute;der &agrave; nos Services) ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>technologie GPS permettant de d&eacute;terminer votre position actuelle (certains de nos services de localisation n&eacute;cessitent vos informations personnelles pour pouvoir fonctionner) ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Partage de vos informations personnelles :</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Toutes vos informations et celles de vos destinataires seront partag&eacute;es avec les personnes suivantes :</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>notre personnel (mais l&rsquo;utilisation qu&rsquo;ils en feront sera limit&eacute;e &agrave; l&rsquo;exercice de leurs missions et en fonction du motif de traitement, y compris (i) pour traiter une demande d&rsquo;enregistrement et d&rsquo;utilisation de nos Services (ii) pour v&eacute;rifier votre identit&eacute; (iii) pour traiter vos transactions (iv) pour suivre, am&eacute;liorer et personnaliser nos Services, le contenu, le marketing et la publicit&eacute; (v) pour fournir nos autres Services et les services clients associ&eacute;s et (vi) pour les enqu&ecirc;tes sur les risques, le d&eacute;pannage, l&rsquo;analyse des donn&eacute;es, les tests, la recherche, et &agrave; des fins statistiques et de sondage) ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Conservation de vos informations personnelles :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous ne conserverons vos informations personnelles que pour la dur&eacute;e n&eacute;cessaire afin d&rsquo;atteindre les objectifs pour lesquels nous les avons collect&eacute;es, y compris pour nous conformer &agrave; toute exigence l&eacute;gale, comptable ou en mati&egrave;re de d&eacute;claration. Pour d&eacute;terminer la p&eacute;riode de conservation appropri&eacute;e des informations personnelles, nous tenons compte notamment des &eacute;l&eacute;ments suivants :</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>obligations et/ou p&eacute;riodes de conservation impos&eacute;es par les lois applicables et/ou par nos r&eacute;gulateurs ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>quantit&eacute;, nature et sensibilit&eacute; des informations personnelles ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>risque potentiel de pr&eacute;judice r&eacute;sultant de l&rsquo;utilisation ou de la divulgation non autoris&eacute;e de vos informations personnelles ; et</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>objectifs pour lesquels nous traitons vos informations personnelles et si nous pouvons atteindre ceux-ci par d&rsquo;autres moyens.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Veuillez noter qu&rsquo;en utilisant nos Services, vous acceptez express&eacute;ment que nous conservions vos donn&eacute;es personnelles (y compris les donn&eacute;es relatives &agrave; vos transactions et &agrave; la collecte/v&eacute;rification de votre identit&eacute;) pendant plus de 5 ans apr&egrave;s la fin de votre relation juridique avec nous. Cela nous permet de d&eacute;tecter et de pr&eacute;venir toute fraude et/ou d&rsquo;autres utilisations illicites de notre Service.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:21px;line-height:150%;font-family:"Arial",sans-serif;'>7. PARTICIPANTS &Agrave; LA RECHERCHE</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Informations personnelles collect&eacute;es :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Si vous participez &agrave; un projet de recherche pour nous (par t&eacute;l&eacute;phone, en personne, par enqu&ecirc;te &eacute;lectronique, notamment), nous conserverons votre nom, vos coordonn&eacute;es et toute autre information personnelle que vous choisissez de nous fournir en participant &agrave; nos projets de recherche.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Utilisation de vos informations personnelles :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous utiliserons ces informations pour nos int&eacute;r&ecirc;ts l&eacute;gitimes, et entre autres pour conduire nos projets de recherche, qui peuvent &eacute;galement nous aider &agrave; am&eacute;liorer et/ou &agrave; d&eacute;velopper nos produits et services.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Partage de vos informations personnelles :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous partagerons ces informations avec les personnes suivantes :</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>divers tiers qui fournissent des logiciels et des outils utilis&eacute;s pour exploiter notre entreprise (courrier &eacute;lectronique, messagerie instantan&eacute;e, gestion des documents/contrats et partage de fichiers, entre autres) ; et</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>des tiers en cas de vente, d&rsquo;acquisition ou de fusion de tout ou partie de nos actifs si vos informations personnelles font partie des actifs transf&eacute;r&eacute;s (dans ce cas, nous vous informerons, ainsi que des choix que vous pouvez faire concernant vos informations personnelles, en diffusant un avis sur notre site).</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Conservation de vos informations personnelles :&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous ne conserverons vos informations personnelles que pour la dur&eacute;e n&eacute;cessaire afin d&rsquo;atteindre les objectifs pour lesquels nous les avons collect&eacute;es, y compris pour nous conformer &agrave; toute exigence l&eacute;gale, comptable ou en mati&egrave;re de d&eacute;claration. Pour d&eacute;terminer la p&eacute;riode de conservation appropri&eacute;e des informations personnelles, nous tenons compte notamment des &eacute;l&eacute;ments suivants :</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>obligations et/ou p&eacute;riodes de conservation impos&eacute;es par les lois applicables et/ou par nos r&eacute;gulateurs ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>quantit&eacute;, nature et sensibilit&eacute; des informations personnelles ;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>risque potentiel de pr&eacute;judice r&eacute;sultant de l&rsquo;utilisation ou de la divulgation non autoris&eacute;e de vos informations personnelles ; et</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>objectifs pour lesquels nous traitons vos informations personnelles et si nous pouvons atteindre ceux-ci par d&rsquo;autres moyens.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:21px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:21px;line-height:150%;font-family:"Arial",sans-serif;'>11. VOS DROITS</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>En ce qui concerne les informations personnelles que nous d&eacute;tenons &agrave; votre sujet, vous b&eacute;n&eacute;ficiez des droits suivants :</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>acc&eacute;der &agrave; vos informations personnelles et aux informations relatives &agrave; leur traitement</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>nous demander de corriger l&rsquo;enregistrement de vos informations personnelles conserv&eacute; par nos soins, s&rsquo;il est inexact (ou de compl&eacute;ter des informations personnelles incompl&egrave;tes)</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>nous demander, dans certains cas limit&eacute;s, de supprimer vos informations personnelles ou de cesser leur traitement</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>vous opposer &agrave; ce que nous traitions vos informations personnelles &agrave; des fins de marketing direct</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>vous opposer aux d&eacute;cisions reposant uniquement sur un traitement automatis&eacute; (profilage, notamment)</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>contester le traitement de vos informations personnelles, justifi&eacute; sur la base de nos int&eacute;r&ecirc;ts l&eacute;gitimes</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>nous demander, dans certains cas limit&eacute;s, de restreindre le traitement des informations personnelles au simple stockage</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>nous demander, dans certains cas limit&eacute;s, de transf&eacute;rer vos donn&eacute;es personnelles &agrave; un autre fournisseur en ligne</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>emp&ecirc;cher tout traitement susceptible de vous porter pr&eacute;judice ou d&rsquo;entra&icirc;ner un dommage pour vous, et nous demander de vous indemniser pour tout dommage que nous aurions pu vous causer en enfreignant les lois sur la PDD)</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&ecirc;tre inform&eacute;(e) de toute violation d&rsquo;informations personnelles susceptible d&rsquo;entra&icirc;ner un risque &eacute;lev&eacute; pour vos droits et libert&eacute;s,</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&bull;&nbsp;</span></strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>d&eacute;poser plainte aupr&egrave;s de l&rsquo;autorit&eacute; comp&eacute;tente en mati&egrave;re de protection des donn&eacute;es.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Vos destinataires b&eacute;n&eacute;ficient &eacute;galement de ces droits au sujet des informations personnelles que nous traitons &agrave; leur sujet. Veuillez coop&eacute;rer avec nous dans le cadre de cette v&eacute;rification d&rsquo;identit&eacute;). Veuillez noter que nous sommes susceptibles d&rsquo;avoir besoin de certaines informations personnelles qui nous permettent de vous fournir les services et/ou les informations que vous demandez ; par cons&eacute;quent, les modifications que vous apportez &agrave; vos pr&eacute;f&eacute;rences (ou les restrictions que vous nous demandez d&rsquo;apporter &agrave; la mani&egrave;re dont nous utilisons les informations personnelles) peuvent affecter les informations que nous serons capables de fournir.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Veuillez &eacute;galement noter que dans certains cas, nous ne pouvons pas cesser d&rsquo;utiliser vos informations personnelles lorsque vous nous le demandez (par exemple, lorsque</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>nous devons les utiliser, car la loi nous y oblige, ou lorsque nous devons les conserver &agrave; des fins r&eacute;glementaires). Dans d&rsquo;autres cas, si nous arr&ecirc;tons ou limitons l&rsquo;utilisation de vos informations personnelles, nous serons dans l&rsquo;impossibilit&eacute; de vous fournir nos</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Services (ex&eacute;cution de transferts d&rsquo;argent, par exemple). Nous vous indiquerons si nous sommes dans l&rsquo;impossibilit&eacute; de donner suite &agrave; votre demande, ou la fa&ccedil;on dont votre demande peut vous affecter, lorsque vous nous contacterez.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:21px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>12. COMMENT NOUS PROT&Eacute;GEONS VOS INFORMATIONS</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>PERSONNELLES</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Nous utilisons des normes accept&eacute;es par le secteur d&rsquo;activit&eacute; pour prot&eacute;ger les informations que vous nous transmettez. Nous avons mis en place la technologie de pour prot&eacute;ger vos informations sensibles (telles que votre num&eacute;ro de compte bancaire, le num&eacute;ro de votre carte de cr&eacute;dit, votre date de naissance et votre num&eacute;ro d&rsquo;identification du gouvernement), transmises notre Application. Nous exigeons &eacute;galement l&rsquo;utilisation d&rsquo;identifiants de s&eacute;curit&eacute; (qui peuvent, par exemple, inclure un nom d&rsquo;utilisateur et un mot de passe) de la part de chaque utilisateur qui souhaite acc&eacute;der &agrave; ses informations sur notre Site et/ou notre</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Application.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Lorsque nous vous avons fourni (ou que vous avez choisi) des identifiants de s&eacute;curit&eacute; (tels qu&rsquo;un mot de passe) qui vous permettent d&rsquo;acc&eacute;der &agrave; certaines parties de notre</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Service, il vous incombe d&rsquo;assurer la confidentialit&eacute; et la s&eacute;curit&eacute; de ces informations.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>De plus, si vous autorisez l&rsquo;acc&egrave;s &agrave; nos Services en utilisant votre empreinte digitale sur votre appareil (par exemple, via la fonctionnalit&eacute; Touch ID d&rsquo;Apple), vous ne devez pas autoriser une autre personne &agrave; enregistrer son empreinte digitale sur cet appareil, car cela pourrait lui permettre d&rsquo;acc&eacute;der &agrave; nos Services et vous pourriez &ecirc;tre tenu(e) responsable de ses actes. Cependant, aucune m&eacute;thode de transmission sur Internet, aucune m&eacute;thode de stockage &eacute;lectronique, n&rsquo;est s&ucirc;re &agrave; 100 %. Par cons&eacute;quent, nous ne pouvons pas garantir une s&eacute;curit&eacute; absolue, et toute transmission d&rsquo;informations</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Personnelles est effectu&eacute;e &agrave; vos propres risques.&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:21px;line-height:150%;font-family:"Arial",sans-serif;'>13. MARKETING DIRECT</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Vous avez le droit de nous demander de ne pas traiter vos informations personnelles &agrave; des fins de marketing. Vous pouvez exercer ce droit &agrave; tout moment, en appliquant simplement les mesures de &laquo; d&eacute;sabonnement &raquo; qui vous sont propos&eacute;es (par exemple, en cliquant sur le lien &laquo; d&eacute;sabonnement &raquo; dans chaque courriel promotionnel que nous vous envoyons). Nous respecterons votre choix et nous nous abstiendrons de vous envoyer ce type de communications. Veuillez noter que si vous nous demandez de ne pas vous contacter par e-mail &agrave; une adresse &eacute;lectronique sp&eacute;cifique, nous conserverons une copie de cette adresse sur une &laquo; liste de suppression &raquo; afin de r&eacute;pondre &agrave; votre demande de non-envoi d&rsquo;e-mails. Vous &ecirc;tes libre de changer &agrave; tout moment vos choix en mati&egrave;re de marketing.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>Vous pouvez &eacute;galement contr&ocirc;ler la fa&ccedil;on dont nous utilisons certaines de vos informations personnelles dans le cadre de nos Services (m&eacute;thode de communication avec vous, par exemple) en confirmant vos pr&eacute;f&eacute;rences dans votre profil. Veuillez noter qu&rsquo;il n&rsquo;est pas possible de d&eacute;sactiver toutes les communications (par exemple, nous pouvons &ecirc;tre amen&eacute;s &agrave; vous envoyer des avis par e-mail concernant nos Services, afin de nous conformer &agrave; nos obligations l&eacute;gales en vertu des lois nationales et des recommandations des r&eacute;gulateurs en droit communautaire.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:150%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-size:16px;line-height:150%;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
    </div>
</template>